# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=200)),
                ('file', models.FileField(upload_to=b'mydocs/', verbose_name=b'videofile')),
            ],
        ),
    ]
